-- 코드를 작성해주세요
SELECT COUNT(FISH_NAME) AS FISH_COUNT
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER';
# GROUP BY FISH_NAME
# HAVING FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER';